---
- name: rabbitmq_ha_config | creating vhost permission
  command: rabbitmqadmin declare permission vhost=/sensu user=sensu configure='.*' write='.*' read='.*'
  run_once: true
  become: true

- name: rabbitmq_ha_config | creating vhost policy
  #command:  rabbitmqadmin declare policy name=ha-sensu pattern="^(results$|keepalives$)" definition='{"ha-mode":"all","ha-sync-mode":"automatic"}' -p /sensu --username=rabbitmqadmin --password=rabbitmqadmin
<<<<<<< HEAD
  command:  rabbitmqadmin -V /sensu declare policy name=ha-sensu pattern="^(results$|keepalives$)" definition='{"ha-mode":"all","ha-sync-mode":"automatic"}' --username="{{item.name}}" --password="{{item.password}}"
  with_items: "{{ rabbitmq_sensu_users }}"
  run_once: true
  become: true

=======
  command:  rabbitmqadmin declare policy name=ha-sensu pattern="^(results$|keepalives$)" definition='{"ha-mode":"all","ha-sync-mode":"automatic"}' -p /sensu --username="{{item.name}}" --password="{{item.password}}"
  with_items: "{{ rabbitmq_users }}"
  run_once: true
  become: true
>>>>>>> bd5be039aec94b7293b47ad39afc4506ca9808b3
