---
- name: rabbitmq_ha_config | creating vhost permission
  command: rabbitmqadmin declare permission vhost=/sensu user=sensu configure='.*' write='.*' read='.*'
  run_once: true
  become: true

- name: rabbitmq_ha_config | creating vhost policy
  #command:  rabbitmqadmin declare policy name=ha-sensu pattern="^(results$|keepalives$)" definition='{"ha-mode":"all","ha-sync-mode":"automatic"}' -p /sensu --username=rabbitmqadmin --password=rabbitmqadmin
  command:  rabbitmqadmin declare policy name=ha-sensu pattern="^(results$|keepalives$)" definition='{"ha-mode":"all","ha-sync-mode":"automatic"}' -p /sensu --username="{{item.name}}" --password="{{item.password}}"
  with_items: "{{ rabbitmq_users }}"
  run_once: true
  become: true
