---
# tasks/Amazon/rabbit.yml: Deploy RabbitMQ
# Specific to Amazon Linux AMI

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Erlang & RabbitMQ are installed
    yum:
      name:
        - erlang
        - rabbitmq-server
      state: present
      enablerepo: epel
