---
# tasks/Ubuntu/redis.yml: Deploy redis
# Specific to Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure redis is installed
    apt:
      name: "{{ redis_pkg_name }}"
      state: "{{ redis_pkg_state }}"
      update_cache: true
